"""
FastAPI application entrypoint for the AI Engine microservice.

Configures CORS, logging, includes routers, and exposes
the /health endpoint.
"""

import logging
import sys

from fastapi import FastAPI
from fastapi.middleware.cors import CORSMiddleware

from app.routers.itinerary import router as itinerary_router

# ── Logging Setup ──────────────────────────────────────────────────

logging.basicConfig(
    level=logging.DEBUG,
    format="%(asctime)s | %(levelname)-8s | %(name)s | %(message)s",
    datefmt="%Y-%m-%d %H:%M:%S",
    stream=sys.stdout,
)
logger = logging.getLogger(__name__)

# ── FastAPI App ────────────────────────────────────────────────────

app = FastAPI(
    title="AI Travels – AI Engine",
    description=(
        "AI-powered travel itinerary generation service. "
        "Receives trip parameters and returns structured day-by-day "
        "itineraries generated by Google Gemini."
    ),
    version="1.0.0",
    docs_url="/docs",
    redoc_url="/redoc",
)

# ── CORS Middleware ────────────────────────────────────────────────

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],  # Restricted in production via env config
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

# ── Routers ────────────────────────────────────────────────────────

app.include_router(itinerary_router)

# ── Health Check ───────────────────────────────────────────────────


@app.get(
    "/health",
    tags=["system"],
    summary="Health check",
    description="Returns the health status of the AI Engine service.",
)
async def health_check() -> dict:
    """Return service health status."""
    return {
        "status": "healthy",
        "service": "ai-engine",
    }


# ── Startup / Shutdown Events ─────────────────────────────────────


@app.on_event("startup")
async def on_startup() -> None:
    """Log service startup."""
    logger.info("AI Engine service started successfully.")


@app.on_event("shutdown")
async def on_shutdown() -> None:
    """Log service shutdown."""
    logger.info("AI Engine service shutting down.")
